import React from 'react';
import { 
  ShieldCheck, 
  FileText, 
  RefreshCw, 
  Mail, 
  Phone, 
  MapPin, 
  AlertCircle, 
  Clock, 
  Building, 
  Lock, 
  CheckCircle2, 
  Scale, 
  HelpCircle,
  Truck,
  FileCheck2,
  AlertTriangle,
  Gavel
} from 'lucide-react';

/* =========================================================================
   1. MASTER TERMS & CONDITIONS (ULTRA-TECHNICAL LEGAL INSTRUMENT)
   ========================================================================= */
export const TermsAndConditions: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-10 text-slate-800 leading-relaxed font-normal">
      {/* Header */}
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-red-50 border border-red-200 text-xs font-black text-[#ED1C24] uppercase tracking-wider">
          <Scale className="w-4 h-4" />
          <span>Statutory Master Service Instrument & Electronic Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-[#002147] tracking-tight uppercase font-display">
          Terms & Conditions of Service
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold uppercase tracking-wider">
          Operating Entity: TRANSED LLP | Formulated Under Section 10A of the Information Technology Act, 2000
        </p>
        <div className="text-[11px] font-mono text-slate-400">
          Document Ref: TND-LLP-TOS-REV-2026-V4 | Legally Enforceable Electronic Record
        </div>
      </div>

      {/* Preamble & Caveat Emptor Notification */}
      <div className="bg-slate-900 text-white rounded-3xl p-6 sm:p-8 space-y-4 shadow-xl border-t-4 border-[#ED1C24]">
        <div className="flex items-center gap-3 text-amber-400 font-black text-sm uppercase tracking-wider">
          <Gavel className="w-5 h-5 text-amber-400 shrink-0" />
          <span>Notice of Binding Legal Contractual Enforceability & Estoppel</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed text-justify">
          PLEASE SCRUTINIZE THIS BINDING LEGAL INSTRUMENT IN ITS ENTIRETY PRIOR TO NAVIGATING, ACCESSING, REGISTERING UPON, OR TRANSACTING ON THIS DIGITAL INFRASTRUCTURE (<strong>"FIITJEE.ONLINE"</strong>). THIS DOCUMENT CONSTITUTES AN ELECTRONIC RECORD GENERATED BY A COMPUTER SYSTEM AND PRODUCED IN ACCORDANCE WITH THE PROVISIONS OF SECTION 2(t), SECTION 10A, AND SECTION 81 OF THE INFORMATION TECHNOLOGY ACT, 2000 (ACT NO. 21 OF 2000), THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OR INFORMATION) RULES, 2011, THE CONSUMER PROTECTION (E-COMMERCE) RULES, 2020, AND THE PROVISIONS OF THE INDIAN CONTRACT ACT, 1872 (ACT NO. 9 OF 1872). THIS INSTRUMENT DOES NOT REQUIRE PHYSICAL OR DIGITAL CRYPTOGRAPHIC SIGNATURES; YOUR AFFIRMATIVE ACT OF ACCESSING, ENROLLING, OR CONSUMING SERVICES HEREIN CONSTITUTES IRREVOCABLE, EXPLICIT ASSENT AND LEGAL ESTOPPEL UNDER SECTION 115 OF THE INDIAN EVIDENCE ACT, 1872.
        </p>
      </div>

      {/* Main Legal Clauses */}
      <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 space-y-10 shadow-sm text-slate-700 text-justify">
        
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">1</span>
            Definitional Taxonomy, Interlocking Covenants & Interpretative Maxims
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            1.1. In this Master Instrument, unless the context repugnantly mandates otherwise:
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-2">
            <li><strong>"Concessionaire" / "Operating Entity" / "Fiduciary"</strong> denotes <strong>TRANSED LLP</strong>, a duly registered Limited Liability Partnership organized under the Limited Liability Partnership Act, 2008 (LLP Identification: LLPIN/Registration on file), having its primary digital administrative infrastructure situated at New Delhi, India.</li>
            <li><strong>"Platform" / "Infrastructure"</strong> denotes the proprietary suite of web applications, database nodes, application programming interfaces (APIs), transaction routing engines, and candidate portals accessible via the uniform resource locator <code>https://fiitjee.online</code> and its correlated cloud endpoints.</li>
            <li><strong>"Candidate" / "Student" / "Data Principal"</strong> denotes the individual student seeking evaluation, diagnostic assessment, testing registration, scholarship determination, or academic admission.</li>
            <li><strong>"User" / "Subscriber" / "Guardian"</strong> denotes any individual accessing the Platform, including parents or legal guardians acting <em>in loco parentis</em> on behalf of minor candidates.</li>
            <li><strong>"Examination" / "Assessment"</strong> designates the diagnostic tests, including but not limited to the Big Bang Edge Test 2026, FIITJEE Talent Reward Exam (FTRE), General Admission Tests, and computer-based diagnostics administered across physical centres or proctored remote conduits.</li>
          </ul>
          <p className="text-xs sm:text-sm leading-relaxed">
            1.2. The rule of <em>contra proferentem</em> shall have no applicability in the judicial or arbitral construction of this Instrument; ambiguities, if any, shall not be construed adversarially against TRANSED LLP as the drafting entity. The interpretative maxims of <em>ejusdem generis</em>, <em>noscitur a sociis</em>, and <em>expressio unius est exclusio alterius</em> shall govern all semantic thresholds herein.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">2</span>
            Concessionaire Scope, Agency Disclaimers & Independent Contractor Status
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            2.1. <strong>TRANSED LLP</strong> operates as an independent technical concessionaire, digital management fiduciary, candidate workflow administrator, and authorized payment processing entity facilitating online assessment admissions, computerized hall ticket issuance, fee reconciliation, and candidate notification management for FIITJEE educational programs.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            2.2. Nothing contained in this Agreement or in the operation of the Platform shall be construed to create any partnership, joint venture, principal-agent relationship, or master-servant covenant between TRANSED LLP and the User. TRANSED LLP exercises sole discretionary sovereignty over the technical architecture, database schemas, cryptographic safeguards, and verification interfaces of the Platform.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">3</span>
            Candidate Pedigree Attestation, Minors & Parens Patriae Warranties
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            3.1. Under the Indian Contract Act, 1872, individuals lacking contractual capacity (including minors who have not attained the age of eighteen years) are incapacitated from executing independently enforceable contracts without parental authorization. Accordingly, wherever a Candidate is a minor, the parent, legal guardian, or person exercising lawful custody over the minor explicitly enters into this Instrument as a co-obligor and indemnifying guarantor <em>in loco parentis</em>.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            3.2. The User warrants, represents, and covenants with absolute strict liability that: (i) all biometric, demographic, and educational credentials submitted—including candidate name, paternal/maternal nomenclature, date of birth, present schooling standard, schooling affiliation, and residence—are bona fide, immaculate, and accurate; (ii) no candidate is registered under alias, false impersonation, or deceitful academic pedigree. Any transgression of this warranty constitutes actionable fraud under Sections 415, 416, and 420 of the Indian Penal Code, 1860, and shall warrant instantaneous summary invalidation of test credentials, cancellation of test slots, and forfeiture of all fees paid without recourse.
          </p>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">4</span>
            Electronic Assessment Allocation, Non-Negotiable Hall Tickets & Proctoring Telemetry
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            4.1. Upon successful execution of registration protocols and financial reconciliation, the Platform generates an <strong>Official Hall Ticket</strong> bearing a unique 19-digit Roll Number, Student Identification Number (SID), encrypted verification matrix, and examination venue particulars. The Official Hall Ticket is non-transferable, non-negotiable, non-assignable, and personal to the designated Candidate.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            4.2. Candidates are obligated to present a pristine, printed manifestation of the Official Hall Ticket alongside government-recognized or institutional photographic identification at the designated examination center. Center administration and proctorial officers reserve unilateral, non-justiciable authority to refuse entry, expel candidates, or impound answer telemetry in any instance of electronic malpractice, prohibited telecommunication paraphernalia, proxy examination, or disorderly conduct.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            4.3. The digital logs generated during user registration, password verification, biometric seat validation, and online testing constitute conclusive electronic evidence admissible under Section 65B of the Indian Evidence Act, 1872.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">5</span>
            Payment Aggregation, Statutory Taxation, Invoicing & Irrevocable Fee Estoppel
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            5.1. All monetary settlements, candidate assessment charges, processing levies, and coupon-adjusted consideration collected via the Platform are gathered directly by <strong>TRANSED LLP</strong> acting through authorized payment aggregation infrastructure (including Cashfree Payments India Pvt. Ltd. and RBI-authorized scheduled banking institutions).
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            5.2. Consideration is stated in Indian Rupees (₹ INR) inclusive of statutory Goods and Services Tax (GST) at prevailing rates. Upon settlement, a computerized Tax Invoice and transaction receipt are deposited into the candidate's portal record.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            5.3. <strong>Irrevocable Fee Estoppel:</strong> The user acknowledges that examination seats, proctorial manpower, compute instances, and question paper matrices are provisioned and earmarked contemporaneously upon transaction authorization. Consequently, the User is permanently estopped from asserting unilateral chargeback claims, payment clawbacks, or transactional reversals with issuing banking corporations without prior written adjudication by TRANSED LLP.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">6</span>
            Intellectual Property Monopoly, Anti-Decompilation & Automated Scraping Preclusion
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            6.1. All diagnostic problem formulations, psychometric test algorithms, mock CBT architectures, examination syllabi, visual interfaces, typographical styling, SVG assets, logos, and digital transcripts available on the Platform are proprietary intellectual property protected under the Copyright Act, 1957, the Trade Marks Act, 1999, and international intellectual property treaties.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            6.2. Users are strictly prohibited from: (a) utilizing automated algorithms, scrapers, headless browsers, cURL scripts, or bots to harvest candidate lists, coupon indices, or exam configurations; (b) de-compiling, reverse engineering, disassembling, or creating derivative testing portals imitating this platform; (c) redistributing examination questions, answer keys, or score rubrics on third-party forums or messaging conduits. Any infringement will be met with immediate injunction proceedings, statutory damages claims, and criminal copyright infringement complaints.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">7</span>
            Telecommunications Consent, Carrier Indemnity & Universal DND Preemption
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            7.1. By completing portal registration and explicitly ticking the telecommunications consent checkbox, the User issues an express, irrevocable affirmative directive under Regulation 4 and Regulation 19 of the Telecom Commercial Communications Customer Preference Regulations, 2018 (TCCCPR, 2018) formulated by the Telecom Regulatory Authority of India (TRAI).
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            7.2. Such affirmative consent shall supersede, preempt, and invalidate any registration of the User's telephone number on the National Customer Preference Register (NCPR / Do-Not-Disturb / DND registry). TRANSED LLP, its educational affiliates, and its carrier SMS/WhatsApp aggregators are authorized to dispatch transactional notifications, examination alerts, Hall Ticket release broadcasts, scorecards, counselling advisories, and preparatory reminders. TRANSED LLP bears zero liability for transmission drops, telecom carrier latency, or spam-filter quarantining.
          </p>
        </section>

        {/* Section 8 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">8</span>
            Disclaimer of Consequential Damages & Strict Statutory Liability Ceiling
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            8.1. THE PLATFORM, ITS EXAMS, ADMIT CARDS, EVALUATION ENGINES, AND ANCILLARY SERVICES ARE PROVIDED STRICTLY ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY NATURE, WHETHER STATUTORY, EXPRESS, OR IMPLIED. TRANSED LLP EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PEDAGOGICAL PURPOSE, AND UNINTERRUPTED AVAILABILITY.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            8.2. IN NO EVENT SHALL TRANSED LLP, ITS PARTNERS, EXECUTIVES, EMPLOYEES, REPRESENTATIVES, OR EDUCATIONAL ALLIES BE LIABLE FOR ANY INCIDENTAL, INDIRECT, SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF ANTICIPATED SCHOLARSHIP, LOSS OF ACADEMIC YEAR, PSYCHOLOGICAL DISTRESS, COMPUTE HARDWARE DOWNTIME, OR TRAVEL EXPENSES) UNDER ANY DOCTRINE OF CONTRACT, TORT, STRICT LIABILITY, OR STATUTE.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            8.3. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS OR ANY OTHER INSTRUMENT, THE AGGREGATE, CUMULATIVE, MAXIMUM MONETARY LIABILITY OF TRANSED LLP ARISING OUT OF OR IN CONNECTION WITH THE PLATFORM, THE EXAMINATION, OR THIS INSTRUMENT SHALL BE STRICTLY CAPPED AND LIMITED TO THE ACTUAL NET EXAMINATION REGISTRATION FEE PAID BY THE SPECIFIC USER FOR THE SPECIFIC CONTESTED TEST TRANSACTION.
          </p>
        </section>

        {/* Section 9 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">9</span>
            Force Majeure, Vis Major, Network Partitioning & Quantum Meruit
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            9.1. TRANSED LLP shall not be deemed in default or breach of this Agreement for any delay, suspension, postponement, or frustration of performance resulting directly or indirectly from acts of God (<em>vis major</em>), pandemics, civil commotion, strikes, state-declared curfews, internet gateway shutdowns, cyber attacks, denial-of-service (DDoS) onslaughts, undersea cable ruptures, power grid collapsing, or statutory regulatory prohibitions beyond its control.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            9.2. In any such circumstance, TRANSED LLP shall schedule compensatory testing dates or alternative examination slots. The principle of <em>quantum meruit</em> shall govern administrative expenses already incurred.
          </p>
        </section>

        {/* Section 10 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">10</span>
            Mandatory Dispute Resolution, Arbitration & Exclusive Judicial Forum
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            10.1. Any claim, dispute, controversy, or difference arising out of, relating to, or concerning the interpretation, performance, breach, termination, or validity of this Master Instrument or portal usage shall be referred to and conclusively resolved by final and binding arbitration administered in accordance with the Arbitration and Conciliation Act, 1996 (Act No. 26 of 1996, as amended).
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            10.2. The arbitral tribunal shall consist of a <strong>Sole Arbitrator</strong> nominated and appointed unilaterally by the designated management partner of <strong>TRANSED LLP</strong>. The seat, place, and legal venue of arbitration shall be exclusively <strong>New Delhi, India</strong>. The arbitral proceedings shall be conducted exclusively in the English language. The award rendered by the Sole Arbitrator shall be final, executory, and non-appealable, binding upon both parties.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            10.3. Subject to the arbitration covenant herein, the civil courts, commercial courts, and tribunals situated exclusively in <strong>New Delhi, India</strong> shall possess sole and exclusive territorial and subject-matter jurisdiction to the exclusion of all other fora across the Republic of India.
          </p>
        </section>

        {/* Section 11 */}
        <section className="space-y-3 pt-4 border-t border-slate-100">
          <h2 className="text-sm font-bold text-[#002147] uppercase tracking-wider">
            Severability, Non-Waiver & Entirety of Instrument
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            If any provision of this Master Instrument is adjudicated by an arbitral tribunal or competent court to be invalid, void, illegal, or unenforceable, such determination shall not impair the validity or enforceability of the remaining provisions, and the contested provision shall be modified to the minimum extent necessary to render it legally valid. Failure or delay by TRANSED LLP to enforce any covenant herein shall never be construed as an acquiescence or waiver thereof.
          </p>
        </section>

      </div>
    </div>
  );
};

/* =========================================================================
   2. PRIVACY POLICY & DATA GOVERNANCE (DPDP ACT 2023 & SPDI PROTOCOL)
   ========================================================================= */
export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-10 text-slate-800 leading-relaxed font-normal">
      {/* Header */}
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-red-50 border border-red-200 text-xs font-black text-[#ED1C24] uppercase tracking-wider">
          <ShieldCheck className="w-4 h-4" />
          <span>Statutory Data Fiduciary Charter & Cryptographic Governance</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-[#002147] tracking-tight uppercase font-display">
          Privacy & Personal Data Policy
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold uppercase tracking-wider">
          Compliance Nexus: Digital Personal Data Protection Act, 2023 & SPDI Rules, 2011
        </p>
        <div className="text-[11px] font-mono text-slate-400">
          Policy Code: TND-DPDP-SEC-2026-V5 | Enterprise Data Processing Addendum
        </div>
      </div>

      {/* Trust Notice */}
      <div className="bg-emerald-950 text-white rounded-3xl p-6 sm:p-8 space-y-4 shadow-xl border-t-4 border-emerald-500">
        <div className="flex items-center gap-3 text-emerald-400 font-black text-sm uppercase tracking-wider">
          <Lock className="w-5 h-5 text-emerald-400 shrink-0" />
          <span>Data Fiduciary Classification & Personal Data Notice</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed text-justify">
          TRANSED LLP ACTS IN THE CAPACITY OF A <strong>"DATA FIDUCIARY"</strong> WITHIN THE PURVIEW OF SECTION 2(i) OF THE DIGITAL PERSONAL DATA PROTECTION ACT, 2023 (ACT NO. 22 OF 2023 - <strong>"DPDP ACT"</strong>) AND AN "INTERMEDIARY" PURSUANT TO SECTION 2(w) OF THE INFORMATION TECHNOLOGY ACT, 2000. THIS CHARTER FORMALIZES THE SPECIFIC CATEGORIES OF PERSONAL DATA PROCESSED, THE TECHNICAL SECURITY MEASURES DEPLOYED, THE RECIPIENT SUB-PROCESSORS, AND THE RIGHTS RESERVED UNTO THE CANDIDATE AND GUARDIAN AS "DATA PRINCIPALS".
        </p>
      </div>

      {/* Detailed Technical Clauses */}
      <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 space-y-10 shadow-sm text-slate-700 text-justify">
        
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">1</span>
            Taxonomy of Ingested Telemetry & Personal Data Classes
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            1.1. In the course of account creation, entrance assessment registration, and candidate evaluation, the Data Fiduciary ingests and cryptographically processes:
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-2">
            <li><strong>Candidate Demographic & Identity Attributes:</strong> Full legal nomenclature, paternal and maternal designations, biological gender, verified date of birth, present educational grade, attending academic institution, and state/pincode particulars.</li>
            <li><strong>Telecommunication Coordinates:</strong> Primary electronic mail address, 10-digit guardian mobile telephone number, secondary contact coordinates, and residential addresses.</li>
            <li><strong>Transactional Tokens & Payment Proofs:</strong> Payment reference nonces, Cashfree order tokens, bank transaction reference codes, and billing summaries. <em>Under no circumstances does TRANSED LLP store or process Primary Account Numbers (PAN), CVVs, card expiration dates, or net banking authentication tokens.</em></li>
            <li><strong>Automated Environmental Telemetry:</strong> Transmission Control Protocol (TCP/IP) addresses, cryptographic session cookies, HTTP request headers, device user-agent strings, reCAPTCHA enterprise tokens, and hardware fingerprint digests.</li>
          </ul>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">2</span>
            Lawful Purpose Specification & Processing Vectors
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            2.1. Under Section 4, Section 5, and Section 6 of the DPDP Act, 2023, data processing is strictly tethered to the following specified lawful purposes:
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-1.5">
            <li>Allocation of examination slots, computerized seating registers, and generation of verifiable Official Hall Tickets.</li>
            <li>Execution of automated computerized evaluations, computation of All India Ranks (AIR), state percentiles, and scholarship determination.</li>
            <li>Direct transactional messaging, carrier SMS dispatch, automated WhatsApp broadcasts, and urgent administrative alerts regarding examination logistics.</li>
            <li>Issuance of statutory tax invoices in compliance with the Central Goods and Services Tax Act, 2017.</li>
            <li>Prevention of proxy impersonation, automated crawler scraping, and computerized fraud.</li>
          </ul>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">3</span>
            Cryptographic Safeguards & Security Architecture
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            3.1. Pursuant to Rule 8 of the Information Technology (SPDI) Rules, 2011, TRANSED LLP has designed and operationalized a comprehensive information security management framework:
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-1.5">
            <li><strong>Transport Layer Security:</strong> All client-to-server and inter-service telemetry is encrypted using TLS 1.3 cryptographic suites with strict HSTS (HTTP Strict Transport Security) enforcement.</li>
            <li><strong>Storage Encryption:</strong> Database records and student profile attributes stored in cloud nodes are encrypted at rest using Advanced Encryption Standard (AES) with 256-bit cryptographic keys (AES-256).</li>
            <li><strong>Access Isolation:</strong> Access to registration data is partitioned using Role-Based Access Controls (RBAC) and restricted strictly to authenticated center administrators under non-disclosure confidentiality covenants.</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">4</span>
            Sub-Processor Disclosures & Sovereign Data Localization
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            4.1. Data is shared strictly on a need-to-know basis with audited third-party technical sub-processors:
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-1.5">
            <li><strong>Payment Aggregators (Cashfree Payments India Pvt. Ltd.):</strong> For PCI-DSS certified payment clearing and tokenization.</li>
            <li><strong>Cloud Infrastructure Providers (Firebase / Google Cloud Platform):</strong> For real-time database synchronisation, encrypted document hosting, and high-availability storage located within sovereign Indian data centre nodes.</li>
            <li><strong>Telecommunication Gateway Aggregators:</strong> For automated delivery of transactional SMS, verification OTPs, and email transcripts.</li>
            <li><strong>Judicial & Law Enforcement Authorities:</strong> Solely upon service of lawful statutory warrants issued under Section 91 of the Code of Criminal Procedure, 1973.</li>
          </ul>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">5</span>
            Data Principal Rights, Revocation Protocols & Statutory Exceptions
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            5.1. Pursuant to Chapter III (Sections 11 to 14) of the DPDP Act, 2023, the Data Principal possesses: (a) the right to access summaries of personal data processed; (b) the right to correction and updating of inaccurate candidate details; (c) the right to grievance redressal.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            5.2. <strong>Statutory Retention Exception:</strong> The right of data erasure or revocation shall not apply to historical examination records, roll number registries, tax invoices, and verification logs that TRANSED LLP is mandated to preserve under the Goods and Services Tax Act, 2017, the Income Tax Act, 1961, or statutory fraud-prevention audits.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3 pt-4 border-t border-slate-100">
          <h2 className="text-sm font-bold text-[#002147] uppercase tracking-wider">
            Nodal Data Protection & Grievance Redressal Officer
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            Pursuant to Section 8(9) of the DPDP Act, 2023 and Rule 5(9) of the SPDI Rules, 2011, grievances concerning data processing, algorithmic tracking, or privacy rights should be formally submitted to:
            <br />
            <strong>Nodal Grievance Redressal Officer:</strong> Compliance Cell, TRANSED LLP
            <br />
            <strong>Physical Registry:</strong> FIITJEE House, 29-A, Kalu Sarai, Sarvapriya Vihar, New Delhi - 110016, India
            <br />
            <strong>Official Communication:</strong> <a href="mailto:support@fiitjee.online" className="text-[#ED1C24] font-bold underline">support@fiitjee.online</a> | <a href="mailto:transedllp@gmail.com" className="text-[#ED1C24] font-bold underline">transedllp@gmail.com</a>
          </p>
        </section>

      </div>
    </div>
  );
};

/* =========================================================================
   3. CANCELLATION & REFUND POLICY (PAYMENT AGGREGATOR APPROVED SLA)
   ========================================================================= */
export const RefundPolicy: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-10 text-slate-800 leading-relaxed font-normal">
      {/* Header */}
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-red-50 border border-red-200 text-xs font-black text-[#ED1C24] uppercase tracking-wider">
          <RefreshCw className="w-4 h-4" />
          <span>Statutory Commercial Settlement & Refund Policy</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-[#002147] tracking-tight uppercase font-display">
          Cancellation & Refund Policy
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold uppercase tracking-wider">
          Merchant of Record: TRANSED LLP | Bank-Aggregator Compliant SLA (5–7 Business Days)
        </p>
      </div>

      {/* SLA Highlight Card */}
      <div className="bg-amber-500/10 border-2 border-amber-500/30 rounded-3xl p-6 sm:p-8 space-y-3">
        <div className="flex items-center gap-2 text-amber-900 font-black text-sm uppercase tracking-wider">
          <Clock className="w-5 h-5 text-amber-700 shrink-0" />
          <span>Statutory Refund Settlement Timeline (5 to 7 Banking Days)</span>
        </div>
        <p className="text-xs sm:text-sm text-slate-700 leading-relaxed text-justify">
          Where a formal refund or transaction adjustment is adjudicated and authorized in writing by <strong>TRANSED LLP</strong> in accordance with the strict criteria set forth below, the monetary consideration will be electronically reversed directly to the original initiating source instrument (Issuing Bank Credit Card, Debit Card, Net Banking Account, or Unified Payments Interface Virtual Payment Address - UPI VPA) within a strict operational timeframe of <strong>5 to 7 business working days</strong>.
        </p>
      </div>

      <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 space-y-8 shadow-sm text-slate-700 text-justify">
        
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">1</span>
            Registration Fees for Diagnostic & Scholarship Examinations
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            1.1. Consideration disbursed for examination slots (including Big Bang Edge Test 2026, FTRE, and admission assessments) is allocated toward individual computer workstation reservation, biometric verification proctoring, printed question paper provisioning, digital hall ticket generation, and evaluative grading infrastructure.
          </p>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-2">
            <li><strong>Cancellation Notice Exceeding 7 Days:</strong> In the event that a formal written cancellation request is submitted at least <strong>7 full calendar days</strong> prior to the scheduled examination date, a refund of 80% of the paid assessment fee shall be authorized, with 20% retained as liquidated administrative processing overhead.</li>
            <li><strong>Cancellation Notice Within 7 Days:</strong> Due to immediate lock-in of testing venue overhead, seat assignments, and proctor rosters, cancellation requests received within 7 days of the scheduled examination or on/after the test date are strictly <strong>non-refundable and non-creditable</strong>.</li>
            <li><strong>Candidate Absenteeism (No-Show):</strong> Unilateral absenteeism on the testing date forfeits all consideration. However, candidates may apply to the admissions committee for slot rescheduling where alternative testing windows exist.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">2</span>
            Erroneous Duplicate or Multiple Transaction Reversals
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            2.1. Where network drops, session timeouts, or telecommunications latency result in duplicate debits for the same candidate roll number or registration record, TRANSED LLP shall issue an immediate <strong>100% full reversal</strong> of the duplicate debited amount without deduction. Upon reporting with verified gateway order identifiers (Cashfree Order ID / Payment Reference), the duplicate charge will be processed within 24 hours and settled within the mandatory 5–7 banking day window.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">3</span>
            Administrative Examination Rescheduling or Cancellation
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            3.1. In the extraordinary event that a test date, center venue, or examination slot is cancelled by TRANSED LLP due to administrative restructuring or force majeure constraints, registered candidates shall be entitled to: (i) immediate compensatory slot allocation on the subsequent test date without supplemental fee; OR (ii) an unconditional <strong>100% full refund</strong> of the paid registration fee credited back to their source payment instrument within 5 to 7 banking days.
          </p>
        </section>

        <section className="space-y-3 pt-4 border-t border-slate-100">
          <h2 className="text-sm font-bold text-[#002147] uppercase tracking-wider">
            Reversal Initiation Mechanism
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            All refunds are remitted strictly via automated electronic banking rails directly to the originating payment card, bank account, or UPI VPA. Cash pay-outs, third-party wallet transfers, or bearer instruments are expressly prohibited by statutory RBI anti-money laundering (AML) directives.
          </p>
        </section>

      </div>
    </div>
  );
};

/* =========================================================================
   4. SHIPPING & DIGITAL SERVICE TRANSMISSION POLICY
   ========================================================================= */
export const ShippingPolicy: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-10 text-slate-800 leading-relaxed font-normal">
      {/* Header */}
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-red-50 border border-red-200 text-xs font-black text-[#ED1C24] uppercase tracking-wider">
          <Truck className="w-4 h-4" />
          <span>Digital Transmission & Electronic Fulfillment Protocol</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-[#002147] tracking-tight uppercase font-display">
          Shipping & Delivery Policy
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold uppercase tracking-wider">
          Operating Entity: TRANSED LLP | Non-Tangible Electronic Service Fulfillment
        </p>
      </div>

      <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 space-y-8 shadow-sm text-slate-700 text-justify">
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">1</span>
            Intangible Electronic Service Architecture
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed">
            1.1. <strong>TRANSED LLP</strong> delivers educational examination slot allocations, computerized assessments, diagnostic evaluations, and candidate portal access. Because these services are purely digital, electronic, and intangible, <strong>no tangible physical commodities or printed packages are dispatched via courier, postal freight, or surface shipping</strong>.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-black text-[#002147] uppercase tracking-wide flex items-center gap-2 border-b border-slate-100 pb-2">
            <span className="w-6 h-6 rounded-full bg-red-100 text-[#ED1C24] flex items-center justify-center text-xs font-bold">2</span>
            Instantaneous Digital Transmission Service-Level Agreement (SLA)
          </h2>
          <ul className="list-disc pl-6 text-xs sm:text-sm space-y-2">
            <li><strong>Official Hall Ticket & Tax Invoice:</strong> Generated and rendered instantaneously on the client browser upon successful payment aggregator webhook validation (0 seconds latency). Candidates are empowered to download and print the document immediately.</li>
            <li><strong>Confirmation Electronic Dispatch:</strong> An encrypted electronic mail containing the Candidate Roll Number, Centre Address, Test Timings, and Hall Ticket download hyperlink is dispatched automatically to the registered email within <strong>0 to 15 minutes</strong> of payment clearance.</li>
            <li><strong>Candidate Vault Accessibility:</strong> Candidates retain 24/7 perpetual digital access via the Student Portal (<code>https://fiitjee.online/student/login</code>) to reprint Hall Tickets, review exam schedules, download syllabus dossiers, or access national scorecards.</li>
          </ul>
        </section>

        <section className="space-y-3 pt-4 border-t border-slate-100">
          <h2 className="text-sm font-bold text-[#002147] uppercase tracking-wider">
            Resolution for Non-Receipt
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            In rare events of recipient email spam-quarantining or telecom gateway downtime, if a digital hall ticket is not visible in the candidate dashboard within 15 minutes of payment debit, the User may instantly reach the merchant admissions desk at <a href="mailto:support@fiitjee.online" className="text-[#ED1C24] font-bold underline">support@fiitjee.online</a> for immediate manual credential dispatch.
          </p>
        </section>
      </div>
    </div>
  );
};

/* =========================================================================
   5. CONTACT US & OFFICIAL STATUTORY MERCHANT DETAILS
   ========================================================================= */
export const ContactUsPage: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-10 text-slate-800 leading-relaxed font-normal">
      {/* Header */}
      <div className="text-center space-y-3 mb-10">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-red-50 border border-red-200 text-xs font-black text-[#ED1C24] uppercase tracking-wider">
          <Building className="w-4 h-4" />
          <span>Statutory Merchant Disclosure & Contact Information</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-[#002147] tracking-tight uppercase font-display">
          Contact Us
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold uppercase tracking-wider">
          Operating Entity & Payment Merchant: TRANSED LLP | National Admissions Helpdesk
        </p>
      </div>

      {/* Grid of Contact Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Merchant Legal Info Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-red-50 text-[#ED1C24] flex items-center justify-center">
            <Building className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-black text-[#002147] uppercase tracking-wider">Legal Entity Identification</h3>
            <p className="text-xs text-slate-400 font-semibold uppercase mt-0.5">Payment Gateway Merchant of Record</p>
          </div>
          <div className="text-xs sm:text-sm text-slate-700 space-y-2 pt-2 border-t border-slate-100">
            <div><span className="font-bold text-slate-900">Entity Name:</span> TRANSED LLP</div>
            <div><span className="font-bold text-slate-900">Industry:</span> Educational Admissions & Examination Technical Administration</div>
            <div><span className="font-bold text-slate-900">Primary Domain:</span> fiitjee.online</div>
            <div><span className="font-bold text-slate-900">Entity Constitution:</span> Registered Limited Liability Partnership (LLPIN on record)</div>
          </div>
        </div>

        {/* Operating Address Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-red-50 text-[#ED1C24] flex items-center justify-center">
            <MapPin className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-black text-[#002147] uppercase tracking-wider">Registered & Operational Office</h3>
            <p className="text-xs text-slate-400 font-semibold uppercase mt-0.5">National Admissions Headquarters</p>
          </div>
          <div className="text-xs sm:text-sm text-slate-700 space-y-1.5 pt-2 border-t border-slate-100">
            <div className="font-bold text-slate-900">FIITJEE House, 29-A, Kalu Sarai</div>
            <div>Sarvapriya Vihar (Near Hauz Khas Metro Station)</div>
            <div>New Delhi - 110016, India</div>
          </div>
        </div>

        {/* Email & Phone Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-red-50 text-[#ED1C24] flex items-center justify-center">
            <Mail className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-black text-[#002147] uppercase tracking-wider">Admissions & Gateway Support</h3>
            <p className="text-xs text-slate-400 font-semibold uppercase mt-0.5">Technical & Billing Inquiries</p>
          </div>
          <div className="text-xs sm:text-sm text-slate-700 space-y-2 pt-2 border-t border-slate-100">
            <div>
              <span className="font-bold text-slate-900">Official Portal Support:</span>
              <br />
              <a href="mailto:support@fiitjee.online" className="text-[#ED1C24] font-bold underline">support@fiitjee.online</a>
            </div>
            <div>
              <span className="font-bold text-slate-900">Merchant Entity Desk:</span>
              <br />
              <a href="mailto:transedllp@gmail.com" className="text-[#ED1C24] font-bold underline">transedllp@gmail.com</a>
            </div>
          </div>
        </div>

        {/* Operating Hours Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-red-50 text-[#ED1C24] flex items-center justify-center">
            <Clock className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-black text-[#002147] uppercase tracking-wider">Admissions Helpdesk Timings</h3>
            <p className="text-xs text-slate-400 font-semibold uppercase mt-0.5">Operating Schedule (Indian Standard Time)</p>
          </div>
          <div className="text-xs sm:text-sm text-slate-700 space-y-1.5 pt-2 border-t border-slate-100">
            <div><span className="font-bold text-slate-900">Monday – Saturday:</span> 09:30 AM to 06:30 PM IST</div>
            <div><span className="font-bold text-slate-900">Sunday (Exam Days):</span> 10:00 AM to 02:00 PM IST</div>
            <div className="text-[11px] text-slate-400 mt-2">National Public Holidays: Emergency email triage operational.</div>
          </div>
        </div>
      </div>
    </div>
  );
};
